# generated by datamodel-codegen:
#   filename:  checkpoint.schema.json

from __future__ import annotations

from datetime import datetime
from typing import Dict, List, Literal, Optional
from uuid import UUID

from pydantic import BaseModel, ConfigDict, RootModel, confloat


class Role(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    role: str
    name: str


class Nth(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    selector: str
    index: int


class Selectors(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    css: Optional[str] = None
    xpath: Optional[str] = None
    text: Optional[str] = None
    role: Optional[Role] = None
    testid: Optional[str] = None
    nth: Optional[Nth] = None
    placeholder: Optional[str] = None


class BoundingBox(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    x: float
    y: float
    width: float
    height: float


class VisibleElement(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    selectors: Selectors
    tag: str
    text_content: Optional[str] = None
    is_visible: bool
    bounding_box: Optional[BoundingBox] = None
    computed_styles: Optional[Dict[str, str]] = None


class RecentApiCall(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    method: str
    url: str
    status: int
    duration_ms: Optional[confloat(ge=0.0)] = None
    request_body_summary: Optional[str] = None
    response_body_summary: Optional[str] = None


class ConsoleError(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    level: str
    message: str
    source: Optional[str] = None


class SelectorsModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    css: Optional[str] = None
    xpath: Optional[str] = None
    text: Optional[str] = None
    role: Optional[Role] = None
    testid: Optional[str] = None
    nth: Optional[Nth] = None
    placeholder: Optional[str] = None


class FormValue(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    selectors: SelectorsModel
    value: str
    checked: Optional[bool] = None
    disabled: bool
    type: str


class FocusedElement(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    selectors: SelectorsModel


class Checkpoint(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal[1]
    checkpoint_id: UUID
    session_id: UUID
    trigger_event_id: UUID
    timestamp: datetime
    url: str
    visible_elements: Optional[List[VisibleElement]] = None
    form_values: Optional[List[FormValue]] = None
    focused_element: Optional[FocusedElement] = None
    page_title: Optional[str] = None
    recent_api_calls: Optional[List[RecentApiCall]] = None
    console_errors: Optional[List[ConsoleError]] = None
    full_snapshot_url: Optional[str] = None


class Model(RootModel[Checkpoint]):
    root: Checkpoint
