# generated by datamodel-codegen:
#   filename:  event.schema.json

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Literal, Optional, Union
from uuid import UUID

from pydantic import BaseModel, ConfigDict, PositiveFloat, RootModel, confloat, conint


class Viewport(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    width: int
    height: int


class Page(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str
    title: Optional[str] = None
    viewport: Optional[Viewport] = None


class Role(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    role: str
    name: str


class Nth(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    selector: str
    index: int


class Selectors(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    css: Optional[str] = None
    xpath: Optional[str] = None
    text: Optional[str] = None
    role: Optional[Role] = None
    testid: Optional[str] = None
    nth: Optional[Nth] = None
    placeholder: Optional[str] = None


class BoundingBox(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    x: float
    y: float
    width: float
    height: float


class Target(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    selectors: Selectors
    tag: str
    attributes: Dict[str, Optional[str]]
    text_content: Optional[str] = None
    bounding_box: Optional[BoundingBox] = None
    is_in_iframe: bool
    iframe_selector: Optional[str] = None


class Modifier(Enum):
    Shift = "Shift"
    Ctrl = "Ctrl"
    Alt = "Alt"
    Meta = "Meta"


class Button(Enum):
    left = "left"
    right = "right"


class Position(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    x: float
    y: float


class Payload(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    modifiers: Optional[List[Modifier]] = None
    force: Optional[bool] = None
    button: Optional[Button] = None
    position: Optional[Position] = None


class Event1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal[1]
    event_id: UUID
    session_id: UUID
    tab_id: UUID
    sequence: conint(ge=0)
    timestamp: datetime
    page: Page
    target: Target
    event_type: Literal["click"]
    payload: Payload


class Direction(Enum):
    up = "up"
    down = "down"
    left = "left"
    right = "right"


class Payload5(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    x: float
    y: float
    delta_x: Optional[float] = None
    delta_y: Optional[float] = None
    direction: Direction


class Payload6(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    value: str


class Payload7(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    previous_value: Optional[str] = None


class Payload8(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    key: str
    repeat: Optional[conint(ge=0)] = None


class Payload9(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    value: str
    delay: Optional[confloat(ge=0.0)] = None


class Payload10(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    value: Optional[str] = None
    label: Optional[str] = None
    index: Optional[conint(ge=0)] = None


class Payload11(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    checked: bool


class Action(Enum):
    copy = "copy"
    cut = "cut"
    paste = "paste"


class Payload12(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    action: Action
    text: Optional[str] = None


class Trigger(Enum):
    link_click = "link_click"
    form_submit = "form_submit"
    js_redirect = "js_redirect"
    history_push = "history_push"
    history_pop = "history_pop"


class Payload13(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    to_url: str
    from_url: Optional[str] = None
    trigger: Trigger


class LoadState(Enum):
    domcontentloaded = "domcontentloaded"
    networkidle = "networkidle"
    load = "load"


class Payload14(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    load_state: LoadState


class Payload15(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str
    opener_tab_id: UUID


class Type(Enum):
    pushState = "pushState"
    replaceState = "replaceState"
    popstate = "popstate"


class Payload16(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str
    type: Type


class Payload17(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    filenames: List[str]
    mimes: List[str]
    sizes: Optional[List[confloat(ge=0.0)]] = None


class Payload18(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    filename: str
    url: Optional[str] = None
    mime: Optional[str] = None


class ElementType(Enum):
    video = "video"
    audio = "audio"


class Payload19(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    element_type: ElementType
    src: str
    current_time: Optional[confloat(ge=0.0)] = None


class DialogType(Enum):
    alert = "alert"
    confirm = "confirm"
    prompt = "prompt"
    beforeunload = "beforeunload"


class Response(Enum):
    OK = "OK"
    Cancel = "Cancel"


class Payload21(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    dialog_type: DialogType
    message: str
    response: Optional[Response] = None
    input_value: Optional[str] = None


class Permission(Enum):
    geolocation = "geolocation"
    notifications = "notifications"
    camera = "camera"
    microphone = "microphone"


class Response1(Enum):
    grant = "grant"
    deny = "deny"


class Payload22(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    permission: Permission
    response: Response1


class Method(Enum):
    GET = "GET"
    POST = "POST"
    PUT = "PUT"
    PATCH = "PATCH"
    DELETE = "DELETE"
    HEAD = "HEAD"
    OPTIONS = "OPTIONS"


class Payload23(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    method: Method
    url: str
    request_headers: Optional[Dict[str, str]] = None
    request_body: Optional[Any] = None
    status: Optional[int] = None
    response_body: Optional[Any] = None
    duration_ms: Optional[confloat(ge=0.0)] = None


class Direction1(Enum):
    sent = "sent"
    received = "received"


class Payload25(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str
    direction: Direction1
    data: str


class Direction2(Enum):
    left = "left"
    right = "right"
    up = "up"
    down = "down"


class EventId(RootModel[UUID]):
    root: UUID


class PageModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str
    title: Optional[str] = None
    viewport: Optional[Viewport] = None


class Items(Enum):
    Shift = "Shift"
    Ctrl = "Ctrl"
    Alt = "Alt"
    Meta = "Meta"


class SchemaVersion(RootModel[Literal[1]]):
    root: Literal[1]


class Sequence(RootModel[conint(ge=0)]):
    root: conint(ge=0)


class SessionId(RootModel[UUID]):
    root: UUID


class TabId(RootModel[UUID]):
    root: UUID


class Selectors1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    css: Optional[str] = None
    xpath: Optional[str] = None
    text: Optional[str] = None
    role: Optional[Role] = None
    testid: Optional[str] = None
    nth: Optional[Nth] = None
    placeholder: Optional[str] = None


class TargetModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    selectors: Selectors1
    tag: str
    attributes: Dict[str, Optional[str]]
    text_content: Optional[str] = None
    bounding_box: Optional[BoundingBox] = None
    is_in_iframe: bool
    iframe_selector: Optional[str] = None


class SelectorsModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    css: Optional[str] = None
    xpath: Optional[str] = None
    text: Optional[str] = None
    role: Optional[Role] = None
    testid: Optional[str] = None
    nth: Optional[Nth] = None
    placeholder: Optional[str] = None


class Timestamp(RootModel[datetime]):
    root: datetime


class TargetModel1(RootModel[Optional[TargetModel]]):
    root: Optional[TargetModel]


class Payload1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    modifiers: Optional[List[Items]] = None
    position: Optional[Position] = None


class Event2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    event_id: EventId
    session_id: SessionId
    tab_id: TabId
    sequence: Sequence
    timestamp: Timestamp
    page: PageModel
    target: TargetModel
    event_type: Literal["dblclick"]
    payload: Payload1


class Event3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    event_id: EventId
    session_id: SessionId
    tab_id: TabId
    sequence: Sequence
    timestamp: Timestamp
    page: PageModel
    target: TargetModel
    event_type: Literal["right_click"]
    payload: Payload1


class Payload3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    position: Optional[Position] = None


class Event4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    event_id: EventId
    session_id: SessionId
    tab_id: TabId
    sequence: Sequence
    timestamp: Timestamp
    page: PageModel
    target: TargetModel
    event_type: Literal["hover"]
    payload: Payload3


class Payload4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    target_selectors: SelectorsModel
    source_position: Optional[Position] = None
    target_position: Optional[Position] = None


class Event5(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    event_id: EventId
    session_id: SessionId
    tab_id: TabId
    sequence: Sequence
    timestamp: Timestamp
    page: PageModel
    target: TargetModel
    event_type: Literal["drag_drop"]
    payload: Payload4


class Event6(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    event_id: EventId
    session_id: SessionId
    tab_id: TabId
    sequence: Sequence
    timestamp: Timestamp
    page: PageModel
    target: Optional[TargetModel] = None
    event_type: Literal["scroll"]
    payload: Payload5


class Event7(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    event_id: EventId
    session_id: SessionId
    tab_id: TabId
    sequence: Sequence
    timestamp: Timestamp
    page: PageModel
    target: TargetModel
    event_type: Literal["fill"]
    payload: Payload6


class Event8(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    event_id: EventId
    session_id: SessionId
    tab_id: TabId
    sequence: Sequence
    timestamp: Timestamp
    page: PageModel
    target: TargetModel
    event_type: Literal["clear"]
    payload: Payload7


class Event9(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    event_id: EventId
    session_id: SessionId
    tab_id: TabId
    sequence: Sequence
    timestamp: Timestamp
    page: PageModel
    target: Optional[TargetModel1] = None
    event_type: Literal["press_key"]
    payload: Payload8


class Event10(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    event_id: EventId
    session_id: SessionId
    tab_id: TabId
    sequence: Sequence
    timestamp: Timestamp
    page: PageModel
    target: TargetModel
    event_type: Literal["type_sequentially"]
    payload: Payload9


class Event11(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    event_id: EventId
    session_id: SessionId
    tab_id: TabId
    sequence: Sequence
    timestamp: Timestamp
    page: PageModel
    target: TargetModel
    event_type: Literal["select_option"]
    payload: Payload10


class Event12(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    event_id: EventId
    session_id: SessionId
    tab_id: TabId
    sequence: Sequence
    timestamp: Timestamp
    page: PageModel
    target: TargetModel
    event_type: Literal["check"]
    payload: Payload11


class Event13(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    event_id: EventId
    session_id: SessionId
    tab_id: TabId
    sequence: Sequence
    timestamp: Timestamp
    page: PageModel
    target: TargetModel
    event_type: Literal["focus"]
    payload: Dict[str, Any]


class Event14(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    event_id: EventId
    session_id: SessionId
    tab_id: TabId
    sequence: Sequence
    timestamp: Timestamp
    page: PageModel
    target: Optional[TargetModel1] = None
    event_type: Literal["clipboard"]
    payload: Payload12


class Event15(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    event_id: EventId
    session_id: SessionId
    tab_id: TabId
    sequence: Sequence
    timestamp: Timestamp
    page: PageModel
    target: Optional[TargetModel1] = None
    event_type: Literal["navigation"]
    payload: Payload13


class Event16(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    event_id: EventId
    session_id: SessionId
    tab_id: TabId
    sequence: Sequence
    timestamp: Timestamp
    page: PageModel
    target: Optional[TargetModel1] = None
    event_type: Literal["page_load"]
    payload: Payload14


class Event17(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    event_id: EventId
    session_id: SessionId
    tab_id: TabId
    sequence: Sequence
    timestamp: Timestamp
    page: PageModel
    target: Optional[TargetModel1] = None
    event_type: Literal["reload"]
    payload: Dict[str, Any]


class Event18(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    event_id: EventId
    session_id: SessionId
    tab_id: TabId
    sequence: Sequence
    timestamp: Timestamp
    page: PageModel
    target: Optional[TargetModel1] = None
    event_type: Literal["tab_open"]
    payload: Payload15


class Event19(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    event_id: EventId
    session_id: SessionId
    tab_id: TabId
    sequence: Sequence
    timestamp: Timestamp
    page: PageModel
    target: Optional[TargetModel1] = None
    event_type: Literal["tab_close"]
    payload: Dict[str, Any]


class Event20(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    event_id: EventId
    session_id: SessionId
    tab_id: TabId
    sequence: Sequence
    timestamp: Timestamp
    page: PageModel
    target: Optional[TargetModel1] = None
    event_type: Literal["history_change"]
    payload: Payload16


class Event21(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    event_id: EventId
    session_id: SessionId
    tab_id: TabId
    sequence: Sequence
    timestamp: Timestamp
    page: PageModel
    target: TargetModel
    event_type: Literal["file_upload"]
    payload: Payload17


class Event22(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    event_id: EventId
    session_id: SessionId
    tab_id: TabId
    sequence: Sequence
    timestamp: Timestamp
    page: PageModel
    target: Optional[TargetModel1] = None
    event_type: Literal["download"]
    payload: Payload18


class Event23(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    event_id: EventId
    session_id: SessionId
    tab_id: TabId
    sequence: Sequence
    timestamp: Timestamp
    page: PageModel
    target: TargetModel
    event_type: Literal["media_play"]
    payload: Payload19


class Payload20(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    element_type: ElementType
    current_time: confloat(ge=0.0)


class Event24(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    event_id: EventId
    session_id: SessionId
    tab_id: TabId
    sequence: Sequence
    timestamp: Timestamp
    page: PageModel
    target: TargetModel
    event_type: Literal["media_pause"]
    payload: Payload20


class Event25(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    event_id: EventId
    session_id: SessionId
    tab_id: TabId
    sequence: Sequence
    timestamp: Timestamp
    page: PageModel
    target: Optional[TargetModel1] = None
    event_type: Literal["dialog"]
    payload: Payload21


class Event26(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    event_id: EventId
    session_id: SessionId
    tab_id: TabId
    sequence: Sequence
    timestamp: Timestamp
    page: PageModel
    target: Optional[TargetModel1] = None
    event_type: Literal["permission_prompt"]
    payload: Payload22


class Event27(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    event_id: EventId
    session_id: SessionId
    tab_id: TabId
    sequence: Sequence
    timestamp: Timestamp
    page: PageModel
    target: Optional[TargetModel1] = None
    event_type: Literal["api_request"]
    payload: Payload23


class Payload24(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    method: Method
    url: str
    status: int
    error_message: Optional[str] = None
    response_body: Optional[Any] = None


class Event28(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    event_id: EventId
    session_id: SessionId
    tab_id: TabId
    sequence: Sequence
    timestamp: Timestamp
    page: PageModel
    target: Optional[TargetModel1] = None
    event_type: Literal["api_error"]
    payload: Payload24


class Event29(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    event_id: EventId
    session_id: SessionId
    tab_id: TabId
    sequence: Sequence
    timestamp: Timestamp
    page: PageModel
    target: Optional[TargetModel1] = None
    event_type: Literal["websocket_message"]
    payload: Payload25


class Payload26(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    position: Position


class Event30(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    event_id: EventId
    session_id: SessionId
    tab_id: TabId
    sequence: Sequence
    timestamp: Timestamp
    page: PageModel
    target: TargetModel
    event_type: Literal["tap"]
    payload: Payload26


class Payload27(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    direction: Direction2
    start: Position
    end: Position


class Event31(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    event_id: EventId
    session_id: SessionId
    tab_id: TabId
    sequence: Sequence
    timestamp: Timestamp
    page: PageModel
    target: Optional[TargetModel1] = None
    event_type: Literal["swipe"]
    payload: Payload27


class Payload28(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scale: PositiveFloat
    center: Position


class Event32(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    event_id: EventId
    session_id: SessionId
    tab_id: TabId
    sequence: Sequence
    timestamp: Timestamp
    page: PageModel
    target: Optional[TargetModel1] = None
    event_type: Literal["pinch_zoom"]
    payload: Payload28


class Event(
    RootModel[
        Union[
            Event1,
            Event2,
            Event3,
            Event4,
            Event5,
            Event6,
            Event7,
            Event8,
            Event9,
            Event10,
            Event11,
            Event12,
            Event13,
            Event14,
            Event15,
            Event16,
            Event17,
            Event18,
            Event19,
            Event20,
            Event21,
            Event22,
            Event23,
            Event24,
            Event25,
            Event26,
            Event27,
            Event28,
            Event29,
            Event30,
            Event31,
            Event32,
        ]
    ]
):
    root: Union[
        Event1,
        Event2,
        Event3,
        Event4,
        Event5,
        Event6,
        Event7,
        Event8,
        Event9,
        Event10,
        Event11,
        Event12,
        Event13,
        Event14,
        Event15,
        Event16,
        Event17,
        Event18,
        Event19,
        Event20,
        Event21,
        Event22,
        Event23,
        Event24,
        Event25,
        Event26,
        Event27,
        Event28,
        Event29,
        Event30,
        Event31,
        Event32,
    ]


class Model(RootModel[Event]):
    root: Event
